openapi: "3.0.0"
info:
    version: "1.0.0"
    title: "SKJSports API"
    description: Backend for SKJSports blog

paths:
    /article?id=articleId:
        parameters:
            - name: articleId
              description: The unique identifier of the article
              in: query
              required: true
              schema:
                  $ref: "#/components/schemas/ArticleId"
        get:
            summary: Retrieve an article's contents, including text and image IDs, by the article's ID
            responses:
                "200":
                    description: The article corresponding to the provided `articleId`
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Article"
                404:
                    description: No article found for the provided `articleId`
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
                500:
                    description: Unexpected error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Error"
components:
    schemas:
        ArticleId:
            description: The unique identifier of a article
            type: string
        Article:
            type: object
            required:
                - id
                - title
                - content
            properties:
                id:
                    $ref: "#/components/schemas/ArticleId"
                title:
                    type: string
                content:
                    type: array
                    items:
                        type: object
                        required:
                            - contentType
                        properties:
                            contentType:
                                type: string
                                description: 'This field takes on the value "text" or "image".'
                            text:
                                type: string
                                description: 'This field only exists if `contentType` is set to "text".'
                            imageId:
                                type: string
                                description: 'This field only exists if `contentType` is set to "image".'

        Error:
            type: object
            required:
                - message
            properties:
                message:
                    description: A human readable error message
                    type: string
    # securitySchemes:
    #     ApiKey:
    #         type: apiKey
    #         in: header
    #         name: X-Api-Key
# security:
#     - ApiKey: []
